export const COUNTRIES_CURRENCY = [
  { country: 'United States', currency: 'USD' },
  { country: 'European Union', currency: 'EUR' },
  { country: 'Japan', currency: 'JPY' },
  { country: 'United Kingdom', currency: 'GBP' },
  { country: 'Switzerland', currency: 'CHF' },
  { country: 'Canada', currency: 'CAD' },
  { country: 'Australia', currency: 'AUD' },
  { country: 'China', currency: 'CNY' },
  { country: 'India', currency: 'INR' },
  { country: 'Brazil', currency: 'BRL' },
  { country: 'Russia', currency: 'RUB' },
  { country: 'South Korea', currency: 'KRW' },
  { country: 'Mexico', currency: 'MXN' },
  { country: 'South Africa', currency: 'ZAR' },
  { country: 'Singapore', currency: 'SGD' },
  { country: 'New Zealand', currency: 'NZD' },
  { country: 'Sweden', currency: 'SEK' },
  { country: 'Norway', currency: 'NOK' },
  { country: 'Denmark', currency: 'DKK' },
  { country: 'Hong Kong', currency: 'HKD' },
  { country: 'Thailand', currency: 'THB' },
  { country: 'Argentina', currency: 'ARS' },
  { country: 'Israel', currency: 'ILS' },
  { country: 'Turkey', currency: 'TRY' },
  { country: 'Saudi Arabia', currency: 'SAR' },
  { country: 'United Arab Emirates', currency: 'AED' },
  { country: 'Egypt', currency: 'EGP' },
  { country: 'Malaysia', currency: 'MYR' },
];
